apiVersion: v1
kind: Service
metadata:
  name: phobos-maptool-service
  labels:
    type: mfe
    name: phobos-maptool
spec:
  selector:
    app: phobos-maptool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002